
/*------------------------------------------------------------------------
    File        : RunABLUnit.p
    Purpose     : Call ABLUnit libraries

    Syntax      :

    Description : 

    Author(s)   : isyed
    Created     : Tue Oct 25 17:13:00 EDT 2016
    Notes       :
  ----------------------------------------------------------------------*/

/* ***************************  Definitions  ************************** */

BLOCK-LEVEL ON ERROR UNDO, THROW.

/* ********************  Preprocessor Definitions  ******************** */


/* ***************************  Main Block  *************************** */


USING Progress.Json.ObjectModel.JsonObject.
USING OpenEdge.ABLUnitHandler.ABLUnitHandlerCore FROM PROPATH.
USING OpenEdge.ABLUnit.Runner.TestConfig.
USING OpenEdge.ABLUnit.Runner.ABLRunner.
USING Progress.Lang.OERequestInfo FROM PROPATH.

DEFINE INPUT PARAMETER configJson AS JSonObject NO-UNDO.
DEFINE INPUT PARAMETER updatefile AS CHARACTER NO-UNDO.
DEFINE INPUT PARAMETER sessguid AS CHARACTER NO-UNDO.
DEFINE INPUT PARAMETER resultsDir AS CHARACTER NO-UNDO.
DEFINE INPUT PARAMETER rec_id AS RECID NO-UNDO.
DEFINE VARIABLE ABLUnitFunctions AS ABLUnitHandlerCore NO-UNDO.
DEFINE VARIABLE testConfig       AS CLASS              TestConfig NO-UNDO.
DEFINE VARIABLE ablRunner        AS ABLRunner          NO-UNDO.


ABLUnitFunctions = NEW ABLUnitHandlerCore().
 
/* Run ABLUnit with the generated config file */
ABLUnitFunctions:InvokeABLUnitTests(configJson,updatefile).     
     
    
/* Validate the XML result generated by ABLUnit and update the record */
ABLUnitFunctions:ValidateResults(sessguid,resultsDir,rec_id). 

CATCH e  AS Progress.Lang.Error :
    DEFINE VARIABLE iLoop AS INTEGER NO-UNDO.
    DO iLoop = 1 TO e:NumMessages:
        PUT UNFORMATTED 
            'ERROR: ' e:GetMessage(iLoop) SKIP.
    END.
    RETURN ERROR e:CallStack.	
		
END CATCH.
